import { CartProvider } from "@/components/cart";
import { NavbarContainer } from "@/components/navbar";
import type { Metadata, Viewport } from "next";
import { Toaster } from "sonner";
import "./globals.css";

// import NavbarButton from "@/components/navbar1/NavbarButton";
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-[200vh]">
        <CartProvider>
          <NavbarContainer />
          <Toaster richColors />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
